#pragma once

namespace Quartz
{
	enum InputAction
	{
		/* General Actions */
		INPUT_ACTION_NONE				= 0x00,

		/* Button Actions */
		INPUT_ACTION_UP					= 0x01,
		INPUT_ACTION_DOWN				= 0x02,
		INPUT_ACTION_PRESSED			= 0x04,
		INPUT_ACTION_RELEASED			= 0x08,
		INPUT_ACTION_REPEAT				= 0x10,

		/* Axis Actions */
		INPUT_ACTION_ACTIVE				= 0x20,
		INPUT_ACTION_MOVE				= INPUT_ACTION_ACTIVE,

		/* Mouse Wheel Actions */
		INPUT_ACTION_MOUSE_WHEEL_UP		= 0x40,
		INPUT_ACTION_MOUSE_WHEEL_DOWN	= 0x80,

		/* Combo Actions */
		INPUT_ACTION_ANY				= 0xFFFF,
		INPUT_ACTION_ANY_UP				= (INPUT_ACTION_UP | INPUT_ACTION_RELEASED),
		INPUT_ACTION_ANY_DOWN			= (INPUT_ACTION_DOWN | INPUT_ACTION_PRESSED | INPUT_ACTION_REPEAT),
		INPUT_ACTION_MOUSE_WHEEL_ANY	= (INPUT_ACTION_MOUSE_WHEEL_UP | INPUT_ACTION_MOUSE_WHEEL_DOWN)
	};

	typedef flags8 InputActions;
}